In [1]:
from core import utils, database, paths
import pandas as pd
import datetime
import os

In [206]:
data : pd.DataFrame | None = database.DatabaseManager().run_query("""select * from tesco_analysts.pmajor1_wtd_for_daily_tableau_test""")

In [2]:
pd.options.display.max_columns = None

In [208]:
data.head()

,fiscal_week,day,country,department,department_name,section,section_name,group,group_name,subgroup,subgroup_name,sales_ex_vat_ty_standard,sales_ex_vat_ty_promo,sales_ex_vat_ty_clearance,sales_ex_vat_ty_others,margin_ty_standard,margin_ty_promo,margin_ty_clearance,margin_ty_others,units_ty_standard,units_ty_promo,units_ty_clearance,units_ty_others,sales_ex_vat_ly_standard,sales_ex_vat_ly_promo,sales_ex_vat_ly_clearance,sales_ex_vat_ly_others,margin_ly_standard,margin_ly_promo,margin_ly_clearance,margin_ly_others,units_ly_standard,units_ly_promo,units_ly_clearance,units_ly_others,sales_lfl_standard,sales_lfl_promo,sales_lfl_clearance,sales_lfl_others,margin_lfl_standard,margin_lfl_promo,margin_lfl_clearance,margin_lfl_others,units_lfl_standard,units_lfl_promo,units_lfl_clearance,units_lfl_others,sales_lflb_standard,sales_lflb_promo,sales_lflb_clearance,sales_lflb_others,margin_lflb_standard,margin_lflb_promo,margin_lflb_clearance,margin_lflb_others,units_lflb_standard,units_lflb_promo,units_lflb_clearance,units_lflb_others,sales_2ylfl_standard,sales_2ylfl_promo,sales_2ylfl_clearance,sales_2ylfl_others,margin_2ylfl_standard,margin_2ylfl_promo,margin_2ylfl_clearance,margin_2ylfl_others,units_2ylfl_standard,units_2ylfl_promo,units_2ylfl_clearance,units_2ylfl_others,sales_2ylflb_standard,sales_2ylflb_promo,sales_2ylflb_clearance,sales_2ylflb_others,margin_2ylflb_standard,margin_2ylflb_promo,margin_2ylflb_clearance,margin_2ylflb_others,units_2ylflb_standard,units_2ylflb_promo,units_2ylflb_clearance,units_2ylflb_others,scan_budget,sales_budget,daily_sales_forecast
0,f2025w48,20260123,CZ,0631,Home seasonal,0636,Autumn,0500,Decorations,0505,CH Decorations,0.000000,0.000000,131.309252,0.0,0.000000,0.000000,-88.424883,0.0,0.0,0.0,67.0,0.0,0.000000,0.000000,9.684240,0.0,0.000000,0.000000,-9.759222,0.0,0.0,0.0,8.0,0.0,0.000000,0.000000,131.309252,0.0,0.000000,0.000000,-88.424883,0.0,0.0,0.0,67.0,0.0,0.000000,0.000000,9.684240,0.0,0.000000,0.000000,-9.759222,0.0,0.0,0.0,8.0,0.0,0.000000,0.000000,131.309252,0.0,0.000000,0.000000,-88.424883,0.0,0.0,0.0,67.0,0.0,0.000000,0.000000,9.684240,0.0,0.000000,0.000000,-9.759222,0.0,0.0,0.0,8.0,0.0,-9408.670691,10674.916164,4054.781026
1,f2025w48,20260123,CZ,0211,Electrical,0217,SDA,0010,Vacuum,0015,Vacuum,1050.282082,88.631168,0.000000,0.0,-60.404762,19.469148,0.000000,0.0,43.0,2.0,0.0,0.0,511.320419,374.011576,-96.959207,0.0,-42.574447,13.807847,6.670691,0.0,36.0,10.0,-1.0,0.0,1050.282082,88.631168,0.000000,0.0,-60.404762,19.469148,0.000000,0.0,43.0,2.0,0.0,0.0,511.320419,374.011576,-96.959207,0.0,-42.574447,13.807847,6.670691,0.0,36.0,10.0,-1.0,0.0,1050.282082,88.631168,0.000000,0.0,-60.404762,19.469148,0.000000,0.0,43.0,2.0,0.0,0.0,511.320419,374.011576,-96.959207,0.0,-42.574447,13.807847,6.670691,0.0,36.0,10.0,-1.0,0.0,4349.855801,12141.650235,13672.976570
2,f2025w48,20260123,HU,0221,Stationery,0229,Writing,0620,Compass,0620,CS1 Compass,417.360016,0.000000,0.000000,0.0,126.141695,0.000000,0.000000,0.0,201.0,0.0,0.0,0.0,65.568106,0.000000,0.000000,0.0,5.634615,0.000000,0.000000,0.0,32.0,0.0,0.0,0.0,417.360016,0.000000,0.000000,0.0,126.141695,0.000000,0.000000,0.0,201.0,0.0,0.0,0.0,65.568106,0.000000,0.000000,0.0,5.634615,0.000000,0.000000,0.0,32.0,0.0,0.0,0.0,417.360016,0.000000,0.000000,0.0,126.141695,0.000000,0.000000,0.0,201.0,0.0,0.0,0.0,65.568106,0.000000,0.000000,0.0,5.634615,0.000000,0.000000,0.0,32.0,0.0,0.0,0.0,11786.237722,35363.245055,31901.860430
3,f2025w48,20260123,HU,0421,Toys & Nursery,0429,Preschool,0500,Others,0505,Others,114.276374,198.165069,173.950531,0.0,58.483897,34.158897,28.347189,0.0,12.0,45.0,31.0,0.0,309.772472,122.296838,238.257175,0.0,101.121365,63.386560,-53.993745,0.0,41.0,21.0,76.0,0.0,114.276374,198.165069,173.950531,0.0,58.483897,34.158897,28.347189,0.0,12.0,45.0,31.0,0.0,309.772472,122.296838,238.257175,0.0,101.121365,63.386560,-53.993745,0.0,41.0,21.0,76.0,0.0,114.276374,198.165069,173.950531,0.0,58.483897,34.158897,28.347189,0.0,12.0,45.0,31.0,0.0,309.772472,122.296838,238.257175,0.0,101.121365,63.386560,-53.993745,0.0,41.0,21.0,76.0,0.0,11215.673056,54686.100888,67905.934178
4,f2025w48,20260123,CZ,0411,Home,0414,Dining,0050,Tea & Coffee,0055,CH Tea &coffee,740.074825,0.000000,1.438296,0.0,442.415158,0.000000,0.507378,0.0,337.0,0.0,1.0,0.0,579.276834,0.000000,9.505701,0.0,337.903756,0.000000,-1.480550,0.0,294.0,0.0,10.0,0.0,740.074825,0.000000,1.438296,0.0,442.415158,0.000000,0.507378,0.0,337.0,0.0,1.0,0.0,579.276834,0.000000,9.505701,0.0,337.903756,0.000000,-1.480550,0.0,294.0,0.0,10.0,0.0,729.549003,0.000000,1.438296,0.0,435.981891,0.000000,0.507378,0.0,335.0,0.0,1.0,0.0,579.276834,0.000000,9.505701,0.0,337.903756,0.000000,-1.480550,0.0,294.0,0.0,10.0,0.0,21347.808182,57273.983568,46524.459724

In [3]:
today = datetime.date.today().strftime('%Y-%m-%d')

In [4]:
data.to_csv(paths.ASSETS_PATH + f"\daily_test_data.csv", index=False)

NameError: name 'data' is not defined

In [5]:
data = pd.read_csv(paths.ASSETS_PATH + f"\daily_test_data.csv")

In [6]:
mod_data = data.copy()

In [7]:
day = mod_data['day'].unique().max()

In [8]:
# If 'day' is a single value (e.g., 20250531), convert to date:
day_int = int(day)  # e.g., 20250531
year = day_int // 10000
month = (day_int % 10000) // 100
d = day_int % 100
datetime.date(year, month, d)

datetime.date(2026, 1, 25)

In [9]:
f'{d} of {month}'

'25 of 1'

In [10]:
#name of the month
month_name = datetime.date(year, month, d).strftime("%m.%d")

month_name

'01.25'

In [11]:
import datetime
import pandas as pd
import requests
from core import database

In [12]:
mod_data.columns

Index(['fiscal_week', 'day', 'country', 'department', 'department_name',
       'section', 'section_name', 'group', 'group_name', 'subgroup',
       'subgroup_name', 'sales_ex_vat_ty_standard', 'sales_ex_vat_ty_promo',
       'sales_ex_vat_ty_clearance', 'sales_ex_vat_ty_others',
       'margin_ty_standard', 'margin_ty_promo', 'margin_ty_clearance',
       'margin_ty_others', 'units_ty_standard', 'units_ty_promo',
       'units_ty_clearance', 'units_ty_others', 'sales_ex_vat_ly_standard',
       'sales_ex_vat_ly_promo', 'sales_ex_vat_ly_clearance',
       'sales_ex_vat_ly_others', 'margin_ly_standard', 'margin_ly_promo',
       'margin_ly_clearance', 'margin_ly_others', 'units_ly_standard',
       'units_ly_promo', 'units_ly_clearance', 'units_ly_others',
       'sales_lfl_standard', 'sales_lfl_promo', 'sales_lfl_clearance',
       'sales_lfl_others', 'margin_lfl_standard', 'margin_lfl_promo',
       'margin_lfl_clearance', 'margin_lfl_others', 'units_lfl_standard',
       'units_lfl_promo', 'units_lfl_clearance', 'units_lfl_others',
       'sales_lflb_standard', 'sales_lflb_promo', 'sales_lflb_clearance',
       'sales_lflb_others', 'margin_lflb_standard', 'margin_lflb_promo',
       'margin_lflb_clearance', 'margin_lflb_others', 'units_lflb_standard',
       'units_lflb_promo', 'units_lflb_clearance', 'units_lflb_others',
       'sales_2ylfl_standard', 'sales_2ylfl_promo', 'sales_2ylfl_clearance',
       'sales_2ylfl_others', 'margin_2ylfl_standard', 'margin_2ylfl_promo',
       'margin_2ylfl_clearance', 'margin_2ylfl_others', 'units_2ylfl_standard',
       'units_2ylfl_promo', 'units_2ylfl_clearance', 'units_2ylfl_others',
       'sales_2ylflb_standard', 'sales_2ylflb_promo', 'sales_2ylflb_clearance',
       'sales_2ylflb_others', 'margin_2ylflb_standard', 'margin_2ylflb_promo',
       'margin_2ylflb_clearance', 'margin_2ylflb_others',
       'units_2ylflb_standard', 'units_2ylflb_promo', 'units_2ylflb_clearance',
       'units_2ylflb_others', 'scan_budget', 'sales_budget',
       'daily_sales_forecast'],
      dtype='object')

In [13]:
last_day_mod_data = mod_data[mod_data['day'] == mod_data['day'].max()]

In [14]:
actual_data = last_day_mod_data

In [15]:
last_day_mod_data

,fiscal_week,day,country,department,department_name,section,section_name,group,group_name,subgroup,subgroup_name,sales_ex_vat_ty_standard,sales_ex_vat_ty_promo,sales_ex_vat_ty_clearance,sales_ex_vat_ty_others,margin_ty_standard,margin_ty_promo,margin_ty_clearance,margin_ty_others,units_ty_standard,units_ty_promo,units_ty_clearance,units_ty_others,sales_ex_vat_ly_standard,sales_ex_vat_ly_promo,sales_ex_vat_ly_clearance,sales_ex_vat_ly_others,margin_ly_standard,margin_ly_promo,margin_ly_clearance,margin_ly_others,units_ly_standard,units_ly_promo,units_ly_clearance,units_ly_others,sales_lfl_standard,sales_lfl_promo,sales_lfl_clearance,sales_lfl_others,margin_lfl_standard,margin_lfl_promo,margin_lfl_clearance,margin_lfl_others,units_lfl_standard,units_lfl_promo,units_lfl_clearance,units_lfl_others,sales_lflb_standard,sales_lflb_promo,sales_lflb_clearance,sales_lflb_others,margin_lflb_standard,margin_lflb_promo,margin_lflb_clearance,margin_lflb_others,units_lflb_standard,units_lflb_promo,units_lflb_clearance,units_lflb_others,sales_2ylfl_standard,sales_2ylfl_promo,sales_2ylfl_clearance,sales_2ylfl_others,margin_2ylfl_standard,margin_2ylfl_promo,margin_2ylfl_clearance,margin_2ylfl_others,units_2ylfl_standard,units_2ylfl_promo,units_2ylfl_clearance,units_2ylfl_others,sales_2ylflb_standard,sales_2ylflb_promo,sales_2ylflb_clearance,sales_2ylflb_others,margin_2ylflb_standard,margin_2ylflb_promo,margin_2ylflb_clearance,margin_2ylflb_others,units_2ylflb_standard,units_2ylflb_promo,units_2ylflb_clearance,units_2ylflb_others,scan_budget,sales_budget,daily_sales_forecast
3045,f2025w48,20260125,HU,221,Stationery,222,Compulsory,20,Color paper,20,Color paper,110.613467,0.000000,11.702956,0.0,54.798077,0.000000,-29.628466,0.0,131.0,0.0,50.0,0.0,86.842165,0.000000,3.431222,0.0,43.027620,0.000000,-12.382460,0.0,111.0,0.0,55.0,0.0,110.613467,0.000000,11.702956,0.0,54.798077,0.000000,-29.628466,0.0,131.0,0.0,50.0,0.0,86.842165,0.000000,3.431222,0.0,43.027620,0.000000,-12.382460,0.0,111.0,0.0,55.0,0.0,110.613467,0.000000,11.702956,0.0,54.798077,0.000000,-29.628466,0.0,131.0,0.0,50.0,0.0,86.842165,0.000000,3.431222,0.0,43.027620,0.000000,-12.382460,0.0,111.0,0.0,55.0,0.0,8898.947464,26700.264899,24086.775467
3046,f2025w48,20260125,HU,421,Toys & Nursery,451,Vehicles,40,Tracks,45,Tracks,161.170985,0.000000,626.461739,0.0,71.260165,0.000000,226.946598,0.0,14.0,0.0,39.0,0.0,197.966981,0.000000,19.285671,0.0,88.064835,0.000000,-2.309637,0.0,14.0,0.0,2.0,0.0,161.170985,0.000000,626.461739,0.0,71.260165,0.000000,226.946598,0.0,14.0,0.0,39.0,0.0,197.966981,0.000000,19.285671,0.0,88.064835,0.000000,-2.309637,0.0,14.0,0.0,2.0,0.0,161.170985,0.000000,626.461739,0.0,71.260165,0.000000,226.946598,0.0,14.0,0.0,39.0,0.0,197.966981,0.000000,19.285671,0.0,88.064835,0.000000,-2.309637,0.0,14.0,0.0,2.0,0.0,8472.915427,41312.786539,51300.020082
3047,f2025w48,20260125,HU,421,Toys & Nursery,427,Outdoor,40,Balls,45,Balls,549.343168,80.921746,17.684892,0.0,229.190533,17.230727,-1.838990,0.0,249.0,25.0,13.0,0.0,665.068851,0.000000,0.000000,0.0,258.731699,0.000000,0.000000,0.0,303.0,0.0,0.0,0.0,549.343168,80.921746,17.684892,0.0,229.190533,17.230727,-1.838990,0.0,249.0,25.0,13.0,0.0,663.073733,0.000000,0.000000,0.0,257.999176,0.000000,0.000000,0.0,302.0,0.0,0.0,0.0,549.343168,80.921746,17.684892,0.0,229.190533,17.230727,-1.838990,0.0,249.0,25.0,13.0,0.0,663.073733,0.000000,0.000000,0.0,257.999176,0.000000,0.000000,0.0,302.0,0.0,0.0,0.0,8472.915427,41312.786539,51300.020082
3048,f2025w48,20260125,SK,434,Other GM,10,Sport,10,Sports Equipm.,10,DVD Players,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
3049,f2025w48,20260125,HU,661,WIGIG,678,Stationery,30,Notebook,35,Bags,0.000000,0.000000,1.163123,0.0,0.000000,0.000000,-4.286433,0.0,0.0,0.0,1.0,0.0,0.000000,46.288972,12.474958,0.0,0.000000,12.841631,-8.684552,0.0,0.0,4.0,1.0,0.0,0.000000,0.000000,1.163123,0.0,0.000000,0.000000,-4.286433,0.0,0.0,0.0,1.0,0.0,0.000000,46.288972,12.474958,0.0,0.000000,12.841631,-8.684552,0.0,0.0,4.0,1.0,0.0,0.000000,0.000000,1.163123,0.0,0.000000,0.000000,-4.286433,0.0,0.0,0.0,1.0,0.0,0.000000,46.288972,12.474958,0.0,0.000000,12.841631,-8.684552,0.0,0.0,4.0,1.0,0.0,828.351437,4860.112891,4020.369818
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5017,f2025w48,20260125,HU,434,Other GM,10,Sport,10,Sports Equipm.,510,Indoor Lights,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
5018,f2025w48,20260125,HU,221,Stationery,251,Office,60,Furniture,60,CS1 Furniture,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,8898.947464,26700.264899,24086.775467
5019,f2025w48,20260125,HU,434,Other GM,10,Sport,10,Sports Equipm.,70,Powertool accesories,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN
5020,f2025w48,20260125,HU,411,Home,415,HomeShop,10,Candles,15,CS1 CH Candles,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,23802.912194,70096.664328,63089.788893
5021,f2025w48,20260125,CZ,434,Other GM,10,Sport,10,Sports Equipm.,20,balls,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN

In [16]:
aggregator = {
    'sales_ty': ['sales_ex_vat_ty_standard', 'sales_ex_vat_ty_promo',
              'sales_ex_vat_ty_clearance', 'sales_ex_vat_ty_others'],
    'sales_ly': ['sales_ex_vat_ly_standard', 'sales_ex_vat_ly_promo',
                 'sales_ex_vat_ly_clearance', 'sales_ex_vat_ly_others'],
    'sales_lfl' : [ 'sales_lfl_standard', 'sales_lfl_promo', 'sales_lfl_clearance','sales_lfl_others'],
    'sales_lflb' : ['sales_lflb_standard', 'sales_lflb_promo', 'sales_lflb_clearance','sales_lflb_others'],
    'margin_ty' : ['margin_ty_standard', 'margin_ty_promo', 'margin_ty_clearance','margin_ty_others'],
    'unit_ty' : [ 'units_ty_standard', 'units_ty_promo','units_ty_clearance', 'units_ty_others'],
    'sales_ly' : ['sales_ex_vat_ly_standard','sales_ex_vat_ly_promo', 'sales_ex_vat_ly_clearance','sales_ex_vat_ly_others'],
    'margin_ly' : ['margin_ly_standard', 'margin_ly_promo','margin_ly_clearance', 'margin_ly_others'],
    'unit_ly' : [ 'units_ly_standard','units_ly_promo', 'units_ly_clearance', 'units_ly_others'],
    'margin_lfl' : ['margin_lfl_standard', 'margin_lfl_promo','margin_lfl_clearance', 'margin_lfl_others'],
    'unit_lfl' : ['units_lfl_standard','units_lfl_promo', 'units_lfl_clearance', 'units_lfl_others'],
    'margin_lflb' : ['margin_lflb_standard', 'margin_lflb_promo','margin_lflb_clearance', 'margin_lflb_others'],
    'unit_lflb' : [ 'units_lflb_standard','units_lflb_promo', 'units_lflb_clearance', 'units_lflb_others'],
    'sales_2ylfl' : ['sales_2ylfl_standard', 'sales_2ylfl_promo', 'sales_2ylfl_clearance','sales_2ylfl_others'],
    'margin_2ylfl' : ['margin_2ylfl_standard', 'margin_2ylfl_promo','margin_2ylfl_clearance', 'margin_2ylfl_others'],
    'unit_2ylfl' : ['units_2ylfl_standard','units_2ylfl_promo', 'units_2ylfl_clearance', 'units_2ylfl_others'],
    'sales_2ylflb' : [ 'sales_2ylflb_standard', 'sales_2ylflb_promo', 'sales_2ylflb_clearance','sales_2ylflb_others'],
    'margin_2ylflb' : ['margin_2ylflb_standard', 'margin_2ylflb_promo','margin_2ylflb_clearance', 'margin_2ylflb_others'],
    'unit_2ylflb' : ['units_2ylflb_standard', 'units_2ylflb_promo', 'units_2ylflb_clearance','units_2ylflb_others'],'sales_budget' : ['sales_budget'],
    'cols' : ['country', 'department', 'department_name','section', 'section_name', 'group', 'group_name', 'subgroup','subgroup_name']
     
}

In [17]:
cols = aggregator['cols']

In [18]:
actual_data.head(2)

,fiscal_week,day,country,department,department_name,section,section_name,group,group_name,subgroup,subgroup_name,sales_ex_vat_ty_standard,sales_ex_vat_ty_promo,sales_ex_vat_ty_clearance,sales_ex_vat_ty_others,margin_ty_standard,margin_ty_promo,margin_ty_clearance,margin_ty_others,units_ty_standard,units_ty_promo,units_ty_clearance,units_ty_others,sales_ex_vat_ly_standard,sales_ex_vat_ly_promo,sales_ex_vat_ly_clearance,sales_ex_vat_ly_others,margin_ly_standard,margin_ly_promo,margin_ly_clearance,margin_ly_others,units_ly_standard,units_ly_promo,units_ly_clearance,units_ly_others,sales_lfl_standard,sales_lfl_promo,sales_lfl_clearance,sales_lfl_others,margin_lfl_standard,margin_lfl_promo,margin_lfl_clearance,margin_lfl_others,units_lfl_standard,units_lfl_promo,units_lfl_clearance,units_lfl_others,sales_lflb_standard,sales_lflb_promo,sales_lflb_clearance,sales_lflb_others,margin_lflb_standard,margin_lflb_promo,margin_lflb_clearance,margin_lflb_others,units_lflb_standard,units_lflb_promo,units_lflb_clearance,units_lflb_others,sales_2ylfl_standard,sales_2ylfl_promo,sales_2ylfl_clearance,sales_2ylfl_others,margin_2ylfl_standard,margin_2ylfl_promo,margin_2ylfl_clearance,margin_2ylfl_others,units_2ylfl_standard,units_2ylfl_promo,units_2ylfl_clearance,units_2ylfl_others,sales_2ylflb_standard,sales_2ylflb_promo,sales_2ylflb_clearance,sales_2ylflb_others,margin_2ylflb_standard,margin_2ylflb_promo,margin_2ylflb_clearance,margin_2ylflb_others,units_2ylflb_standard,units_2ylflb_promo,units_2ylflb_clearance,units_2ylflb_others,scan_budget,sales_budget,daily_sales_forecast
3045,f2025w48,20260125,HU,221,Stationery,222,Compulsory,20,Color paper,20,Color paper,110.613467,0.0,11.702956,0.0,54.798077,0.0,-29.628466,0.0,131.0,0.0,50.0,0.0,86.842165,0.0,3.431222,0.0,43.027620,0.0,-12.382460,0.0,111.0,0.0,55.0,0.0,110.613467,0.0,11.702956,0.0,54.798077,0.0,-29.628466,0.0,131.0,0.0,50.0,0.0,86.842165,0.0,3.431222,0.0,43.027620,0.0,-12.382460,0.0,111.0,0.0,55.0,0.0,110.613467,0.0,11.702956,0.0,54.798077,0.0,-29.628466,0.0,131.0,0.0,50.0,0.0,86.842165,0.0,3.431222,0.0,43.027620,0.0,-12.382460,0.0,111.0,0.0,55.0,0.0,8898.947464,26700.264899,24086.775467
3046,f2025w48,20260125,HU,421,Toys & Nursery,451,Vehicles,40,Tracks,45,Tracks,161.170985,0.0,626.461739,0.0,71.260165,0.0,226.946598,0.0,14.0,0.0,39.0,0.0,197.966981,0.0,19.285671,0.0,88.064835,0.0,-2.309637,0.0,14.0,0.0,2.0,0.0,161.170985,0.0,626.461739,0.0,71.260165,0.0,226.946598,0.0,14.0,0.0,39.0,0.0,197.966981,0.0,19.285671,0.0,88.064835,0.0,-2.309637,0.0,14.0,0.0,2.0,0.0,161.170985,0.0,626.461739,0.0,71.260165,0.0,226.946598,0.0,14.0,0.0,39.0,0.0,197.966981,0.0,19.285671,0.0,88.064835,0.0,-2.309637,0.0,14.0,0.0,2.0,0.0,8472.915427,41312.786539,51300.020082

In [19]:
budget_df = mod_data.drop_duplicates(['sales_budget'])

In [20]:
actual_budget = actual_data.drop_duplicates(['sales_budget'])

### Collect totals

In [21]:
def grouper_totaler(df : pd.DataFrame,group_index=len(cols) ,only_total: bool=True, values : list = aggregator['sales_ty']):
    #--- Create grouping by Country ---
    needed_cols = cols[:group_index]
    df2 = df.groupby(by=needed_cols)[values].sum().reset_index().sort_values([needed_cols[0],], ascending=False)
    prefix = values[0].split("_")[:2]
    df2[f'Total_{prefix}'] = df2[values].sum(axis=1)
    df2.columns = df2.columns.str.replace(r"[\[\]\.,'\"]", "", regex=True)
    df2.columns = df2.columns.str.replace("[' ']","_", regex=True)
    if only_total:
        return df2.loc[:, needed_cols + [df2.columns[-1]]]
    else:
        return df2

In [22]:
total_sales_lfl = grouper_totaler(actual_data,group_index=1,values = aggregator['sales_lfl'])
total_sales_lflb = grouper_totaler(actual_data, group_index=1, values=aggregator['sales_lflb'])
total_sales_by_country = grouper_totaler(actual_data, group_index=1, values=aggregator['sales_ty'])

#TOTAL budget and forecast numbers
sales_forecast = actual_budget['daily_sales_forecast'].sum()
sales_budget = actual_budget['sales_budget'].sum()
total_sales = total_sales_by_country.iloc[:,1].sum()

#Versus numbers
vs_budget = total_sales - sales_budget
vs_budget_perc = (total_sales / sales_budget -1)*100
vs_forecast = total_sales - sales_forecast
vs_forecast_perc = (total_sales / sales_forecast -1) *100 


best_sales_country = total_sales_by_country.sort_values(by=total_sales_by_country.columns[1],ascending=False).iloc[0,0] 



total_promo_sales_lfl = actual_data.groupby('country')['sales_lfl_promo'].sum().reset_index()
total_promo_sales_lflb = actual_data.groupby('country')['sales_lflb_promo'].sum().reset_index()

total_clearance_sales_lfl = actual_data.groupby('country')['sales_lfl_clearance'].sum().reset_index()
total_clerance_sales_lflb = actual_data.groupby('country')['sales_lflb_clearance'].sum().reset_index()

In [23]:
def lflzator(df1 : pd.DataFrame,df2 : pd.DataFrame):
    df3 = df1.merge(df2, on='country')
    df3['Sales_lfl'] = df1.iloc[:,1] - df2.iloc[:,1]
    df3['Total_sales_lfl%'] = (df1.iloc[:,1] / df2.iloc[:,1] -1 )*100
    df3 = df3.sort_values('Sales_lfl', ascending=False)
    return df3.iloc[:, [0,3,4]]

In [24]:
def extract_top_lfl(df: pd.DataFrame, top_n: int = 3) -> dict:
    """
    Visszaadja a legjobb országokat és az LFL értékeiket.

    Args:
        df (pd.DataFrame): Kétszlopos dataframe, ahol az első az ország, a második az LFL érték.
        top_n (int): Hány országot adjon vissza (alapértelmezés 3).

    Returns:
        dict: Például {'best': ('CZ', 3.2), 'second': ('HU', 1.8), 'third': ('SK', 0.9)}
    """
    result = {}
    ranks = ['best', 'second', 'third', 'fourth', 'fifth']
    for i in range(min(top_n, len(df))):
        result[ranks[i]] = (df.iloc[i, 0], df.iloc[i, 2])
    return result

In [25]:
total_sales_lfl_real = lflzator(total_sales_lfl, total_sales_lflb)
total_promo_sales_lfl_real = lflzator(total_promo_sales_lfl,total_promo_sales_lflb)
total_clearance_sales_lfl_real = lflzator(total_clearance_sales_lfl, total_clerance_sales_lflb)

In [26]:
country_lfl = extract_top_lfl(total_sales_lfl_real,3)
best_lfl_country, best_lfl_country_value = country_lfl['best']
second_lfl_country, second_lfl_country_value = country_lfl['second']
third_lfl_country, third_lfl_country_value = country_lfl['third']

In [27]:
country_promo_lfl = extract_top_lfl(total_promo_sales_lfl_real)
best_promo_lfl_country, best_promo_lfl_country_value = country_promo_lfl['best']
second_promo_lfl_country, second_promo_lfl_country_value = country_promo_lfl['second'] 
third_promo_lfl_country, third_promo_lfl_country_value = country_promo_lfl['third']

In [28]:
country_clearance_lfl = extract_top_lfl(total_promo_sales_lfl_real)
best_clearance_lfl_country, best_clearance_lfl_country_value = country_clearance_lfl['best']
second_clearance_lfl_country, second_clearance_lfl_country_value = country_clearance_lfl['second'] 
third_clearance_lfl_country, third_clearance_lfl_country_value = country_clearance_lfl['third']

In [29]:
total_ce_lfl = (total_sales_lfl['Total_sales_lfl'].sum() / total_sales_lflb['Total_sales_lflb'].sum() -1 )*100
ce_promo_lfl = (actual_data['sales_lfl_promo'].sum() / actual_data['sales_lflb_promo'].sum()-1)*100 
ce_range_lfl = (actual_data['sales_lfl_standard'].sum() / actual_data['sales_lflb_standard'].sum()-1)*100 
ce_clearance_lfl = (actual_data['sales_lfl_clearance'].sum() / actual_data['sales_lflb_clearance'].sum()-1)*100

In [30]:
best_lfl_country_value

12.659708592715102

In [39]:
total_sales_string = f"""
You are a financial analyst creating a short executive summary for senior management about Central Europe GM division (CE: HU, SK, CZ) sales results in {month_name} which is the last day data with last year same period performance.
Use 3 or 5 sentences. Avoid bullet points. Focus on deviation vs. budget, context insights.

Figures:
- Total Sales: {total_sales:,.0f}£
- Budget: {sales_budget:,.0f}£
- Forecast: {sales_forecast:,.0f}
- Variance vs Budget: {vs_budget:,.0f}£ and {vs_budget_perc:.2f}%
- Variance vs Forecast : {vs_forecast:,.0f} and {vs_forecast_perc:,.2f}
- Total CE Sales LFL: {total_ce_lfl:,.2f}%
- Total CE Range(not promo or clearance) LFL: {ce_range_lfl:,.2f}
- Total CE promo LFL: {ce_promo_lfl:,.2f} 
- Total CE clereance LFL: {ce_clearance_lfl:,.2f}
- Top-performing country: {best_sales_country}
- Country with best LFL: {best_lfl_country}
- Best LFL performance: {best_lfl_country_value:,.2f}%
- Second in LFL country is: {second_lfl_country}, value: {second_lfl_country_value:,.2f}%
- Third in LFL country is: {third_lfl_country}, value: {third_lfl_country_value:,.2f}%
- Best clearance lfl: {best_clearance_lfl_country}, value: {best_clearance_lfl_country_value:,.2f}%
- Second clearance lfl: {second_clearance_lfl_country}, value: {second_clearance_lfl_country_value:,.2f}%
- Third clearance lfl: {third_clearance_lfl_country}, value: {third_clearance_lfl_country_value:,.2f}%

The questions what you have to give an answer:
- What were the sales?
- Which country was the main driver, and what was the key uplift (promo, range, or clearance)?
- What other underlying relationships or contributing factors could there be?

Format output as a professional financial narrative paragraph.
Add **line breaks between logical sentences** so that each insight starts on a new line.
Do not use "Company" word, its just a division peformances
"""

In [40]:
total_sales_string.split('\n')

['',
 'You are a financial analyst creating a short executive summary for senior management about Central Europe GM division (CE: HU, SK, CZ) sales results in 01.25 which is the last day data with last year same period performance.',
 'Use 3 or 5 sentences. Avoid bullet points. Focus on deviation vs. budget, context insights.',
 '',
 'Figures:',
 '- Total Sales: 786,643£',
 '- Budget: 674,810£',
 '- Forecast: 656,430',
 '- Variance vs Budget: 111,832£ and 16.57%',
 '- Variance vs Forecast : 130,213 and 19.84',
 '- Total CE Sales LFL: 7.12%',
 '- Total CE Range(not promo or clearance) LFL: 2.76',
 '- Total CE promo LFL: 5.86 ',
 '- Total CE clereance LFL: 65.55',
 '- Top-performing country: HU',
 '- Country with best LFL: HU',
 '- Best LFL performance: 12.66%',
 '- Second in LFL country is: SK, value: 4.37%',
 '- Third in LFL country is: CZ, value: -1.42%',
 '- Best clearance lfl: CZ, value: 14.38%',
 '- Second clearance lfl: HU, value: 3.91%',
 '- Third clearance lfl: SK, value: 1.50%',
 '',
 'The questions what you have to give an answer:',
 '- What were the sales?',
 '- Which country was the main driver, and what was the key uplift (promo, range, or clearance)?',
 '- What other underlying relationships or contributing factors could there be?',
 '',
 'Format output as a professional financial narrative paragraph.',
 'Add **line breaks between logical sentences** so that each insight starts on a new line.',
 'Do not use "Company" word, its just a division peformances',
 '']

In [ ]:
daily_result = utils.analyse_financial_summaries(prompt_text=total_sales_string,model='martain7r/finance-llama-8b:q4_k_m')

In [ ]:
longer_period_result = utils.analyse_financial_summaries(prompt_text=total_sales_string,model='martain7r/finance-llama-8b:q4_k_m')

' \n\nCentral Europe GM division (CE: HU, SK, CZ) sales results in 01.25 were strong with total sales of 786,643£, surpassing both the budget of 674,810£ and forecast of 656,430£ by a significant margin.\n\nThe key uplift came from the top-performing country Hungary (HU), where a combination of solid range performance (2.76 LFL) and effective promotions (5.86 LFL) drove total CE sales to an impressive 7.12% LFL growth.\nHowever, clearance sales in Czechia (CZ) were also strong at 14.38 LFL, demonstrating the power of promotional events when executed well.\n\nWhile SK was not as dominant on a unit basis, its overall performance was still healthy with an LFL range of 4.37%, showcasing the potential for growth across all three markets in the coming months.\n\nA detailed analysis of sales trends and underlying drivers is crucial to fully understand these results and inform future strategic decisions.\n'

In [43]:
output_file = os.path.join(paths.ASSETS_PATH, "ai_daily_summary.md")

with open(output_file, "w", encoding="utf-8") as f:
    f.write("# AI Daily Summary\n\n")
    f.write(result)
    f.write("\n")

print(f"Markdown summary successfully saved to: {output_file}")

Markdown summary successfully saved to: C:\Users\pmajor1\OneDrive - Tesco\Business Planning\automatization\ControlPanel_script_runner\framework_assets\ai_daily_summary.md

In [44]:
for r in result.split('\n'):
    print(r)

Central Europe GM division (CE: HU, SK, CZ) sales results in 01.25 were strong with total sales of 786,643£, surpassing both the budget of 674,810£ and forecast of 656,430£ by a significant margin.

The key uplift came from the top-performing country Hungary (HU), where a combination of solid range performance (2.76 LFL) and effective promotions (5.86 LFL) drove total CE sales to an impressive 7.12% LFL growth.
However, clearance sales in Czechia (CZ) were also strong at 14.38 LFL, demonstrating the power of promotional events when executed well.

While SK was not as dominant on a unit basis, its overall performance was still healthy with an LFL range of 4.37%, showcasing the potential for growth across all three markets in the coming months.

A detailed analysis of sales trends and underlying drivers is crucial to fully understand these results and inform future strategic decisions.